language: cpp

cache: ccache

# Only get the current repository state
git:
  depth: false

# Test both clang and gcc
compiler:
  - gcc
  - clang

# Test both linux, and, osx
os:
  - linux
  - osx

# Install requirements with apt
addons:
  apt:
    packages:
    - cmake # Actually already installed by default
    - libsfml-dev
  homebrew:
    packages:
    - cmake # Actually already installed by default
    - sfml
    - ccache

# Build Matrix
jobs:
  fast_finish: true
  include:
  - os: windows
    env:
    - CMAKE_GENERATOR="Visual Studio 15 2017" VCPKG_DEFAULT_TRIPLET=x86-windows
    - CMAKE_GENERATOR="Visual Studio 15 2017 Win64" VCPKG_DEFAULT_TRIPLET=x64-windows
    before_install:
    - powershell ./.travis/before_install.ps1
    install:
    - powershell "C:\dev\vcpkg\vcpkg install sfml"
  - stage: Coverage
    os: linux
    compiler: g++
    cache: false
    before_script:
    - pip install --user cpp-coveralls
    - mkdir build && cd build
    script:
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..
    - cmake --build .
    - ctest -C Coverage
    - cd ..
    after_success:
    - coveralls -e "doc/" -E ".*test.*" -E ".*CMakeFiles.*"

before_script:
  - cmake --version
  - mkdir build && cd build

# Actually check if it works
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest -j2 -V -C Debug
